import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;


/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */
public class Editor extends HttpServlet {
    /**
     * The Servlet constructor
     * 
     * @see javax.servlet.http.HttpServlet#HttpServlet()
     */
    public Editor() {}

    public void init() throws ServletException
    {
        /*  write any servlet initialization code here or remove this function */
        // setting up database connection
        

    }
    
    public void destroy()
    {
        /*  write any servlet cleanup code here or remove this function */
    }

    /**
     * Handles HTTP GET requests
     * 
     * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"

        // getting database connection
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return;
        }

        Connection c = null;
        Statement  s = null; 
        ResultSet rs = null; 

        try {
    
            /* create an instance of a Connection object */
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", ""); 
			s = c.createStatement();
			/* You can think of a JDBC Statement object as a channel
			sitting on a connection, and passing one or more of your
			SQL statements (which you ask it to execute) to the DBMS*/

            }
        catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        }

        String action = request.getParameter("action");
        String username = request.getParameter("username");
        String cmd = "";
        if (action.equals("list")){
            
            ArrayList<String> titles = new ArrayList<String>();
            ArrayList<String> dates_created = new ArrayList<String>();
            ArrayList<String> dates_modified = new ArrayList<String>();
            
            // we query all the articles from the page with that username
           
            try {
                cmd = "SELECT * FROM Posts WHERE username = '" + username + "';"; 
                rs = s.executeQuery(cmd);

                // unpack the results

                while (rs.next()){
                    titles.add(rs.getString("title"));
                    dates_created.add(rs.getString("created"));
                    dates_modified.add(rs.getString("modified"));
                }
            }
            catch (SQLException ex){
                System.out.println("SQLException caught");
                System.out.println("---");
                while ( ex != null ) {
                    System.out.println("Message   : " + ex.getMessage());
                    System.out.println("SQLState  : " + ex.getSQLState());
                    System.out.println("ErrorCode : " + ex.getErrorCode());
                    System.out.println("---");
                    ex = ex.getNextException();
                    }
            }
            request.setAttribute("titles", titles);
            request.setAttribute("dates_created", dates_created);
            request.setAttribute("dates_modified", dates_modified);
            request.setAttribute("username", username);
            // request.setAttribute("nBlogs", titles.size())
            request.getRequestDispatcher("/list.jsp").forward(request, response);
        }
        else if(action.equals("open")){
            request.getRequestDispatcher("/edit.jsp").forward(request, response);
        }
    }
    
    /**
     * Handles HTTP POST requests
     * 
     * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your POST method handling code here
	// currently we simply show the page generated by "edit.jsp"

        request.getRequestDispatcher("/edit.jsp").forward(request, response);
        // request.getRequestDispatcher("/list.jsp").forward(request, response);
    }
}

